data:
  productsFile: products.csv
dynamodb:
  productsTableName: GoApp.ProductsTest
  endpoint:
cloudsearch:
  endpoint:
aws:
  region: us-west-1
  credentials_file_path: nofile 
  credentials_name: default