data:
  productsFile: products.csv
dynamodb:
  productsTableName: GoApp.ProductsTest
  endpoint:
cloudsearch:
  endpoint: no-endpoint.us-west-1.cloudsearch.amazonaws.com
aws:
  region: us-west-1
  credentials_file_path: nofile 
  credentials_name: default