dynamodb:
  productsTableName: GoApp.Products
cloudsearch:
  endpoint: search-goproducts-domain-kg3aqdlqa7sttwc2e5vobmhkki.us-west-2.cloudsearch.amazonaws.com
aws:
  region: us-west-2
  credentials_file_path: /Users/rehnerd/.aws/credentials
  credentials_name: default